### PR TITLE
Fix typo in `clear()` method of `Node`

### PR DESCRIPTION
**Pull request by epatters**

### CODE REVIEW

**Comment by MatejBransky** [comment]
Thanks 👍

**Comment by epatters** [comment]
Thanks for merging. Do you mind cutting a new NPM release with this patch?

**Comment by MatejBransky** [comment]
Published. Sorry for my late reply. I'm working now with KaTeX which is much faster than MathJax. For example I have a lot of problem with unexpected errors in MathJax if you try to update equation based on inputs. With KaTeX I don't have any problems. It just works and it has much simpler API for use with React.

The only downside is that you need to write math in LaTeX which is not so easy as ASCIIMath..but I've got used to it.

P.S.: I'm using custom KaTeX component which is based on react-katex.

**Comment by epatters** [comment]
Thanks!

I'm not too familiar with KaTeX. I'll look into it. I write math in LaTeX myself so that's not a problem.

**Pull request merged**
